### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by anishmenon** [livekit/egress#345]
**Describe the bug**
While requesting livekit-cli start-track-egress --request room-composite.json 
i'm getting EgressID: EG_3UzEqE7DtZ9a Status: EGRESS_STARTING.
But its raising an error on Egress docker.

**Egress Version**
What version are you running?
v1.6.0

**room-composite.json**
```

{
  "room_name": "mxxxxd3-standup-call",
  "track_id": "TR_VCf7WP7uviGNYx",
  "file": {
      
      "filepath": "out/track-test.mp4",
      "s3": {
        "access_key": "",
        "secret": "",
        "region": "us-east-1",
        "bucket": ""
      }
  }
}
```

**egress config.yaml**
   
```

log_level: debug
api_key: access_token
api_secret:
ws_url: wss://URL
insecure: false


redis:
    address: 
    db: 0
    username: default
    password:
    use_tls: true
s3:
    access_key:
    secret: 
    region: us-east-1
    # endpoint:
    bucket: lkbk
```

**Logs**

`
   WARN    egress  service/handler_deprecated.go:145       egress failed   {"nodeID": "NE_KBH9nyimMXGh", "handlerID": "EGH_k3kCwaYyeJ6d", "clusterID": "", "egressID": "EG_XcbrVakMMr4p", "egressID": "EG_XcbrVakMMr4p", "request_type": "track", "output_type": "file", "error": "could not establish signal connection"}
`
