### ISSUE TITLE
[BUG] Egress stops working locally since revision #414

### ISSUE THREAD

**Issue by braveyao** [livekit/egress#434]
**Describe the bug**
I'm running egress locally on my mac which works well in the past until I did a update yesterday. So I notice the room recording failure starts since #414 with the below error logs.
Track egress, i.e. recording an audio track, still works fine.

**Egress Version**
Since revision #414. Revisions #413 and earlier work fine.

**Egress Request**
Post the request here (be sure to remove any PII).

**Additional context**
use docker latest images .
MBP M2

**Logs**
2023-07-19T17:25:32.979Z	WARN	egress	service/handler.go:198	egress failed	{"nodeID": "NE_EVj7YMEHgL9X", "handlerID": "EGH_hz99XUBtKa22", "clusterID": "", "egressID": "EG_5tt6i8YwRirv", "egressID": "EG_5tt6i8YwRirv", "request_type": "room_composite", "output_type": "file", "error": "chrome failed to start:\n[35:35:0719/172532.957399:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.\n[0719/172532.960767:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)\n[0719/172532.960788:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)\n"}

**Comment by frostbyte73** [comment]
Add `--cap-add=SYS_ADMIN` to your `docker run` command

**Comment by braveyao** [comment]
That works! Many thanks!

**Comment by crapthings** [comment]
```yaml
# This docker-compose requires host networking, which is only available on Linux
# This compose will not function correctly on Mac or Windows
services:
  caddy:
    image: livekit/caddyl4
    command: run --config /etc/caddy.yaml --adapter yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./caddy.yaml:/etc/caddy.yaml
      - ./caddy_data:/data
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  livekit-egress:
    image: livekit/egress:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - EGRESS_CONFIG_FILE=/out/config.yaml
    volumes:
      - ./egress.yaml:/out/config.yaml
    cap_add:
      - CAP_SYS_ADMIN
  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf
```


this is docker compose file
