### ISSUE TITLE
[BUG] Stuck on starting docker container 

### ISSUE THREAD

**Issue by farleycanve** [livekit/egress#616]
**Describe the bug**
When I start docker-compose for egress, it stuck on the line: 
"pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit"

**Egress Version**
1.8.0

**Additional context**

- Docker version 20.10.7, build f0df350
- docker-compose version 1.23.2, build 1110ad01 
- egress.yaml:
```
redis:
  address: 192.168.1.4:6479
  username: ""
  password: ""
  db: 0
  use_tls: false
  sentinel_master_name: ""
  sentinel_username: ""
  sentinel_password: ""
  sentinel_addresses: []
  cluster_addresses: []
  max_redirects: null
api_key: API1234567
api_secret: example_secret
insecure: true
ws_url: ws://192.168.1.4:7880
log_level: debug
 # optional egress duration limits - once hit, egress will end with status EGRESS_LIMIT_REACHED
session_limits:
  file_output_max_duration: 10h
  stream_output_max_duration: 10h
  segment_output_max_duration: 12h`
```
- docker-compose.yaml:
```
version: "3.7"
services:
  livekit:
    image: livekit/livekit-server:v1.5.2
    container_name: livekit
    command: --config /etc/livekit.yaml
    restart: always
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  redis:
    image: redis:7-alpine
    container_name: redis-livekit
    command: redis-server /etc/redis.conf
    restart: always
    network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf
  egress:
    image: livekit/egress:v1.8.0
    container_name: rg-egress
    restart: always
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    network_mode: "host"
    volumes:
      - ./egress.yaml:/etc/egress.yaml
    cap_add:
      - SYS_ADMIN

```

**Logs of Egress container**
```
+ rm -rf '/home/egress/tmp/*'
+ rm -rf /var/run/pulse /var/lib/pulse /home/egress/.config/pulse /home/egress/.cache/xdgr/pulse
+ pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit
```
Log inside container:
`ps aux | grep egress`
<img width="877" alt="Screen Shot 2024-02-26 at 14 15 47" src="https://github.com/livekit/egress/assets/65661466/ec234e4a-8dc3-4fb2-82f7-7bf8b1ebb469">
