### ISSUE TITLE
[BUG] failed to change state to PLAYING

### ISSUE THREAD

**Issue by mibrahimy** [livekit/egress#638]
**Describe the bug**
 When I post a start track egress like this

```
 curl -X POST http://127.0.0.1:7880/twirp/livekit.Egress/StartTrackEgress \
        -H "Authorization: Bearer sometoken" \
        -H 'Content-Type: application/json' \
        -d '{"room_name":"localroom","file":{"filepath": "/out/test/"}, "track_id": "TR_abc"}'

```

`livekit-cli list-egress --api-key key --api-secret somesecret
`
![image](https://github.com/livekit/egress/assets/7117319/b8dc4051-eace-4173-bb36-307a46f715af)

**Egress Version**
I am using the following docker setup
```

version: "3.9"
services:
  livekit:
    image: livekit/livekit-server:v1.5
    command: --config ./livekit.yaml --node-ip 127.0.0.1
    container_name: livekit
    restart: always
    ports:
      - '7880:7880'
      - '7881:7881'
      - '7882:7882/udp'
    volumes:
      - /home/mi/mi_workspace/livekit/docker/livekit/livekit.yaml:/livekit.yaml

  # livekit_ingress:
  #   image: livekit/ingress
  #   command: --config ./livekit-ingress.yaml
  #   container_name: livekit_ingress
  #   restart: always
  #   ports:
  #     - 1935:1935
  #     - 8080:8080
  #   depends_on: 
  #     - redis
  #   volumes:
  #     - /home/mi/mi_workspace/livekit/docker/ingress/livekit-ingress.yaml:/livekit-ingress.yaml
  livekit_egress:
    image: livekit/egress
    command: --security-opt seccomp=chrome-sandboxing-seccomp-profile.json
    container_name: livekit_egress
    restart: always
    environment:
      EGRESS_CONFIG_FILE: ./livekit-egress.yaml
    depends_on:
      - redis
    volumes:
      - /home/mi/mi_workspace/livekit/docker/egress/livekit-egress.yaml:/livekit-egress.yaml
      - /home/mi/mi_workspace/livekit/recordings:/out

  redis:
    container_name: redis
    image: redis/redis-stack
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
    
volumes:
  redisdata:

```
**Egress Request**
Posted above.
**Additional context**
I am running this setup on my local machine. Logs' screenshot attached below.

**Logs**
![image](https://github.com/livekit/egress/assets/7117319/096c75c7-9ea8-4000-b431-8722681080cd)
