### ISSUE TITLE
[BUG] Corrupted Video and Audio in Egress Recordings Despite Correct Encoding Settings and Sufficient Resources

### ISSUE THREAD

**Issue by aireis** [livekit/egress#872]
**Describe the bug**
The egress service is producing corrupted or low-quality recordings despite using appropriate encoding settings. The video appears distorted, and the audio is either missing or noisy. The issue persists even after scaling the server to 8 vCPUs and reducing the encoding quality to 420p at 10 fps.

**Egress Version**
Version: latest (Docker image: livekit/egress:latest)

**Egress Request**
Here’s the RoomCompositeEgressRequest configuration being used:
```go
req := &livekit.RoomCompositeEgressRequest{
    RoomName:  roomID,
    Layout:    "grid",
    AudioOnly: false,
    Options: &livekit.RoomCompositeEgressRequest_Advanced{
        Advanced: &livekit.EncodingOptions{
            Width:        720,   // 420p resolution (720x420)
            Height:       420,
            Framerate:    10,    // 10 fps
            VideoBitrate: 1000,  // 1000 kbps video bitrate
            AudioBitrate: 128,   // 128 kbps audio bitrate
            AudioCodec:   livekit.AudioCodec_AAC,
            VideoCodec:   livekit.VideoCodec_H264_MAIN,
        },
    },
    FileOutputs: []*livekit.EncodedFileOutput{
        {
            Filepath: "/recordings/recording.mp4", // Local file path
        },
    },
}
```
also tried with
```go
req := &livekit.RoomCompositeEgressRequest{
    RoomName:  roomID,
    Layout:    "grid",
    AudioOnly: false,
    Options: &livekit.RoomCompositeEgressRequest_Preset{
        Preset: livekit.EncodingOptionsPreset_PRESET_720P,
   },
    FileOutputs: []*livekit.EncodedFileOutput{
        {
            Filepath: "/recordings/recording.mp4", // Local file path
        },
    },
}
```

**Additional context**
- Server Specs: Google Cloud n2-standard-8 (8 vCPUs, 32 GB memory).
- Docker Compose Configuration:
```
services:
  egress:
    image: livekit/egress:latest
    restart: unless-stopped
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    volumes:
      - ./recordings:/recordings
      - ./config/egress.yaml:/etc/egress.yaml
    networks:
      - common
    depends_on:
      - redis
    cap_add:
      - CAP_SYS_ADMIN
    extra_hosts:
      - "livekit:${HOST_IP}"
```
- egress config file:
```
cpu_cost: # optionally override cpu cost estimation, used when accepting or denying requests
  room_composite_cpu_cost: 8.0
  room_composite_cpu_limit: 8.0
redis:
    address: redis:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
api_key: ${LIVEKIT_API_KEY}
api_secret: ${LIVEKIT_API_SECRET}
ws_url: ws://livekit:7880
```

**Logs**
```
egress-1  | 2025-03-09T02:55:55.000000Z    INFO    egress  source/web.go:294       chrome: START_RECORDING {"nodeID": "NE_tEBw3brZTYDQ", "handlerID": "EGH_woPVJXeKi2Dv", "clusterID": "", "egressID": "EG_mekDauJApnyS"}
egress-1  | 2025-03-09T02:55:55.000000Z    INFO    egress  pipeline/watch.go:240   pipeline playing        {"nodeID": "NE_tEBw3brZTYDQ", "handlerID": "EGH_woPVJXeKi2Dv", "clusterID": "", "egressID": "EG_mekDauJApnyS"}
egress-1  | 2025-03-09T02:55:55.000000Z    INFO    egress  info/io.go:178  egress_active   {"nodeID": "NE_tEBw3brZTYDQ", "clusterID": "", "egressID": "EG_mekDauJApnyS", "requestType": "room_composite", "outputType": "segments", "error": "", "code": 0, "details": ""}
egress-1  | 2025-03-09T02:55:55.000000Z    INFO    egress  info/io.go:178  egress_ending   {"nodeID": "NE_tEBw3brZTYDQ", "clusterID": "", "egressID": "EG_mekDauJApnyS", "requestType": "room_composite", "outputType": "segments", "error": "", "code": 0, "details": "End reason: StopEgress API"}
egress-1  | 2025-03-09T02:55:55.000000Z    INFO    egress  pipeline/watch.go:120   pipeline received EOS   {"nodeID": "NE_tEBw3brZTYDQ", "handlerID": "EGH_woPVJXeKi2Dv", "clusterID": "", "egressID": "EG_mekDauJApnyS"}
egress-1  | 2025-03-09T02:55:55.000000Z    INFO    egress  info/io.go:178  egress_complete {"nodeID": "NE_tEBw3brZTYDQ", "clusterID": "", "egressID": "EG_mekDauJApnyS", "requestType": "room_composite", "outputType": "segments", "error": "", "code": 0, "details": "End reason: StopEgress API"}
```

**ffprobe Output:**
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'recording.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomiso2
    creation_time   : 2025-03-09T02:55:55.000000Z
    encoder         : x264
  Duration: 00:00:48.31, start: 0.000000, bitrate: 202 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 5 kb/s (default)
    Metadata:
      creation_time   : 2025-03-09T02:55:55.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m, progressive), 720x420 [SAR 1:1 DAR 12:7], 194 kb/s, 10 fps, 10 tbr, 1k tbn (default)
    Metadata:
      creation_time   : 2025-03-09T02:55:55.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```

**The recording preview:**

![Image](https://github.com/user-attachments/assets/2def7726-817c-4d75-bf76-a62a4717781b)
